version: "1.0"

services:
  frontend:
    container_name: guardian-frontend
    image: guardian-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    container_name: guardian-backend
    image: guardian-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GUARDIAN_DB_HOST=guardian-postgres
      - GUARDIAN_DB_PORT=5432
      - GUARDIAN_DB_USER=admin
      - GUARDIAN_DB_PASSWORD=123
      - GUARDIAN_DB_NAME=guardian
    ports:
      - "8010:8010"
    depends_on:
      - postgres
  postgres:
    container_name: guardian-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: guardian
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local
